### ISSUE TITLE
work

### ISSUE THREAD

**Issue by rafalohaki** [railken/mangafox#1]
is it still working?

**Comment by railken** [comment]
I'm not maintaining since years, but i will check in a few hours and come back to you

**Comment by railken** [comment]
Fixed two issues in v1.1.10, all unit tests are working now @rafalohaki

**Comment by rafalohaki** [comment]
wow thanks

**Comment by rafalohaki** [comment]
btw i got here from looking at source code content of plugin to wordpress
https://codecanyon.net/item/ultimate-web-novel-and-manga-scraper/34167486

**Comment by railken** [comment]
np, thanks for the info of the plugin
